name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenicate to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}

      - name: Upload static site to S3
        run: |
          aws s3 sync ./index.html s3://${{secrets.BUCKET_NAME}}
          aws s3 sync ./css s3://${{secrets.BUCKET_NAME}}
          aws s3 sync ./404.html s3://${{secrets.BUCKET_NAME}}
