name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenicate to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key-id: ${{ secrets.AWS_SECRET_KEY_ID }}
